### ISSUE TITLE
esphome encryption key instructions

### ISSUE THREAD

**Issue by norrland** [psvanstrom/esphome-p1reader#64]
Use encryption key rather than password for api access. Using password is deprecated.

Something like:
```
api:
  encryption:
    key: !secrets encryption_key
```

**Comment by pumpagubben** [comment]
A random generated encryption key can be obtained here: https://esphome.io/components/api.html
Typo above in code, no s in "!secret". Home assistant will automatically prompt to enter the new key. 

```
# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key
    #  password: !secret hass_api_password
```
