### ISSUE TITLE
ESP32-C3 Compile Error

### ISSUE THREAD

**Issue by 314159-r** [psvanstrom/esphome-p1reader#72]
### Compiling p1reader for a SeeedStudio XIAO ESP32C3 with the "esp-idf" framework fails.
I recently got a Wemos D1 device up and running fine with your p1eader. Very nice... But I want a device with external antenna, so I wanted to try to make this work with a XIAO ESP32C3. 
I got this error when compiling using the "esp-idf" framework. I first tried to compile with the default arduino framework, but it it doesn't seem to support the UART component for ESP32C3.

I get the following error when compiling: (log file attached)
```
In file included from src/main.cpp:54:
src/p1reader.h: In member function 'void P1Reader::readP1Message()':
src/p1reader.h:262:21: error: 'Serial' was not declared in this scope
           int len = Serial.readBytesUntil('\n', buffer, BUF_SIZE);
                     ^~~~~~
src/p1reader.h:262:21: note: suggested alternative: 'erfl'
           int len = Serial.readBytesUntil('\n', buffer, BUF_SIZE);
                     ^~~~~~
```

The essential parts of my config: (yaml file attached)
```
esphome:
  name: ${device_name}
  includes:
    - p1reader.h    
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin:
    number: 20  # GPIO20, D7, RX
    inverted: true
```
I'm running this with ESPhome "stand alone", without Home Assistant on a Debian 11 system. My Home Assistant is running on a raspberry Pi 3b+, and it has issues with incompatible compiler for ESP32C3 in the "esp-idf" framework (riscv32-esp-elf-gcc -- broken)

Compiling with just the UART component but without p1reader.h, works fine.

[log-esp32c3-p1reader_esp-idf.txt](https://github.com/psvanstrom/esphome-p1reader/files/11359396/log-esp32c3-p1reader_esp-idf.txt)
[elmataren_yaml.txt](https://github.com/psvanstrom/esphome-p1reader/files/11359399/elmataren_yaml.txt)
