### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by HenkeGoransson** [psvanstrom/esphome-p1reader#80]
I have a weird issue.
My values updates every second. I believe it used to update every 10 seconds before?
I been running this since without change for 2,5years.

Is there a way to change update intervall?

**Comment by Beaky2000** [comment]
I have noticed the same thing with my Sagemcom T211 / Ellevio meter. It used to update every 10 seconds but now updates every second if RTS is constantly high (which it is with this project). This change is in the meter.

I have made a fork of this project, which lets you select update frequency by connecting the RTS signal to a GPIO, which seems to work well with most, but not all, meters. Obviously you would need to modify your ESP module for this to work: https://github.com/Beaky2000/esphome-p1mini

**Comment by HenkeGoransson** [comment]
Thanks alot!

**Comment by jagheterfredrik** [comment]
I've noticed the same behavior with my Ellevio smart meter, I updated the YAML and let esphome do the filtering, removing the need to modify the hardware setup:
```
    - name: "Cumulative Active Import"
      filters:
       - throttle: 9.5s
      unit_of_measurement: kWh
      accuracy_decimals: 3
      state_class: "total_increasing"
      device_class: "energy"
```

**Comment by psvanstrom** [comment]
This isn't caused by a change in the component, sensor values are published once per telegram received from the meter, so the update rate follows how often your meter sends data. Your meter almost certainly had a firmware update (or was replaced) and now sends a telegram every second instead of every 10 seconds.

The component's polling interval isn't the right way to slow this down as it only controls how fast the UART buffer is drained (auto-tuned so it can keep up with the meter), so forcing it slower would just cause buffer overflows and CRC errors, not slower updates.

To throttle how often values reach Home Assistant, use a standard ESPHome sensor filter on the sensors you care about:

```
sensor:
  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_import:
      name: "Momentary Active Import"
      filters:
        - throttle_average: 10s   # average over 10s, publish once (good for power/current/voltage)
    cumulative_active_import:
      name: "Cumulative Active Import"
      filters:
        - throttle: 10s           # just drop intermediate values (fine for meter totals)
```

Use throttle_average for the momentary/instantaneous values (power, current, voltage) and throttle for the cumulative meter totals. Apply it to each sensor you want to slow down.
